### PR TITLE
updates to mct_driver and nuopc_driver

### PR DESCRIPTION
**Pull request by mvertens**
Major updates to both caps. New files have been created in both cap directories so that no longer are using the files in  coupled_driver/.
```
- MOM_ocean_model.F90 (corresponds to coupled_driver/ocean_model_MOM.F90)
- MOM_surface_forcing.F90 (corresponds to coupled_driver/MOM_surface_forcing.F90)
```

Also - for the mct cap have removed the inlining in ocn_comp_mct.F90 code and introduced new copies into ice_ocean_boundary

Note that these changes should result in bfb answers for the mct cap.

### CODE REVIEW

**Comment by mvertens** [comment]
@alperaltuntas - I believe I have fixed the trailing spaces.

**Comment by alperaltuntas** [comment]
I got an error compiling this PR with the mct driver.

```
/gpfs/fs1/work/altuntas/cesm.sandboxes/cesm2.sbx.mom6/components/mom/MOM6/config_src/coupled_driver/ocean_model_MOM.F90(518): error #6784: The number of actual arguments cannot be greater than the number of dummy arguments.   [CONVERT_IOB_TO_FLUXES]
```

 I made the following changes in mct_driver/MOM_ocean_model.F90 and it compiles fine now. is there a reason why the arguments of the shelf_calc_flux call have changed and calls to add_shelf_forces are removed with this PR? Are there similar changes elsewhere?

```
--- a/config_src/mct_driver/MOM_ocean_model.F90
+++ b/config_src/mct_driver/MOM_ocean_model.F90
@@ -56,7 +56,7 @@ use MOM_tracer_flow_control, only : call_tracer_flux_init
 use MOM_variables,           only : surface
 use MOM_verticalGrid,        only : verticalGrid_type
 use MOM_ice_shelf,           only : initialize_ice_shelf, shelf_calc_flux, ice_shelf_CS
-use MOM_ice_shelf,           only : ice_shelf_end, ice_shelf_save_restart
+use MOM_ice_shelf,           only : add_shelf_forces, ice_shelf_end, ice_shelf_save_restart
 use coupler_types_mod,       only : coupler_1d_bc_type, coupler_2d_bc_type
 use coupler_types_mod,       only : coupler_type_spawn, coupler_type_write_chksums
 use coupler_types_mod,       only : coupler_type_initialized, coupler_type_copy_data
@@ -472,7 +472,9 @@ subroutine update_ocean_model(Ice_ocean_boundary, OS, Ocean_sfc, &
 
     ! Add ice shelf fluxes
     if (OS%use_ice_shelf) then
-      call shelf_calc_flux(OS%sfc_state, OS%forces, OS%fluxes, OS%Time, time_step, OS%Ice_shelf_CSp)
+      !call shelf_calc_flux(OS%sfc_state, OS%forces, OS%fluxes, OS%Time, time_step, OS%Ice_shelf_CSp)
+      call shelf_calc_flux(OS%sfc_state, OS%fluxes, OS%Time, time_step, OS%Ice_shelf_CSp)
+      call add_shelf_forces(OS%grid, OS%Ice_shelf_CSp, OS%forces)
     endif
 
     ! GMM, check ocean_model_MOM.F90 to enable the following option
@@ -495,7 +497,9 @@ subroutine update_ocean_model(Ice_ocean_boundary, OS, Ocean_sfc, &
                                OS%sfc_state, OS%restore_salinity, OS%restore_temp)
 
     if (OS%use_ice_shelf) then
-      call shelf_calc_flux(OS%sfc_state, OS%forces, OS%flux_tmp, OS%Time, time_step, OS%Ice_shelf_CSp)
+      !call shelf_calc_flux(OS%sfc_state, OS%forces, OS%flux_tmp, OS%Time, time_step, OS%Ice_shelf_CSp)
+      call shelf_calc_flux(OS%sfc_state, OS%flux_tmp, OS%Time, time_step, OS%Ice_shelf_CSp)
+      call add_shelf_forces(OS%grid, OS%Ice_shelf_CSp, OS%forces)
     endif
 ```

**Comment by mvertens** [comment]
HI Alper,

I'm just running into the same issue - and I was sure that I resolved it.
But I moved to hobart for my testing and only worked on nuopc and did not
push it back from cheyenne. I think your changes are all that is needed.
Sorry for the confusion. Hopefully, everything will be bfb - if not I'll
got back and get this resolved.

Mariana

**Comment by alperaltuntas** [comment]
Mariana,

There are also a few more stylistic issues, such as ```use``` statements without ```only``` keyword, and lines exceeding 120 characters. I will fix those before merging, but I'd be nice to keep the MOM6 standard in mind for future PRs. See: https://github.com/NOAA-GFDL/MOM6/wiki/Code-style-guide

**Comment by mvertens** [comment]
Great!!! That's really good news. Sorry for the compilation problem you ran
into.

**Pull request merged**
