### PR TITLE
(*) Merge GFDL to main (2022-10-27) 

### PR DESCRIPTION
**Pull request by gustavo-marques**
A full description of what's been merged is provided at https://github.com/mom-ocean/MOM6/pull/1586

This PR will change answers for the CESM tests because the following parameters were removed from MOM_parameter_doc.all:
* KDML
* KVML

In MOM_interface, these parameters were set to KVML = 1.0E-04 m2 s-1  and KDML = 0.0 m2 s-1. I've verified that setting KVML = 0.0 (which is equivalent to what's being done in this PR) does not result in significant changes in a G compset. Differences in key metrics over 10 years are documented in [these](https://github.com/gustavo-marques/cesm_mom6_progress/tree/master/updated_defaults_nov22/notebooks) notebooks. 

To accommodate these changes, this PR must be evaluated in conjunction with https://github.com/ESCOMP/MOM_interface/pull/128

### CODE REVIEW

**Comment by gustavo-marques** [comment]
Cherry-picked https://github.com/NCAR/MOM6/pull/229/commits/380864138fb936e3e0bd76bb5155d74200e89db8 to fix issue in GH actions due to MPI installation.

**Comment by marshallward** [comment]
@gustavo-marques I am going to do an update to `main` today in a separate PR.  That will also fix the macos issue.  Should we do it that way rather than cherry-picks in this PR?

**Comment by marshallward** [comment]
Actually, it looks like the macos change was unneeded here, I was confusing the regression test.

Let's just go with this for now and we'll do things properly next time it happens.

**Comment by alperaltuntas** [comment]
testing...

**Review by alperaltuntas — APPROVED** [review]

**Pull request merged**
