### PR TITLE
Major updates to the LBD module

### PR DESCRIPTION
**Pull request by gustavo-marques**
This PR is a major update to the lateral boundary diffusion module. The scheme now relies on regridding/remapping techniques which guarantee that diffusion is applied laterally regardless of the vertical coordinate system. The following steps, which are also shown in the figure below, summarize what has been implemented here: 

1) remap tracer to a z* grid (LBD grid)
2) calculate diffusive tracer fluxes (F) in the LBD grid using a layer by layer approach
3) remap fluxes to the velocity points of the native grid
4) Apply flux limiter and update tracer by adding the divergence of F

image

Additional modules (MOM.F90 and MOM_tracer_hor_diff.F90) are modified to allow  H_subroundoff, which is available in `verticalGrid_type`,  to be accessed from LBD. 

This PR changes answers for all CESM/MOM6 tests where USE_LATERAL_BOUNDARY_DIFFUSION = True.

### CODE REVIEW

**Comment by alperaltuntas** [comment]
testing ...

**Review by alperaltuntas — APPROVED** [review]
aux_mom.cheyenne intel & gnu. all pass, b4b

**Comment by gustavo-marques** [comment]
> aux_mom.cheyenne intel & gnu. all pass, b4b

Interesting. I expected answers changes for tests with USE_LATERAL_BOUNDARY_DIFFUSION = True.

**Comment by alperaltuntas** [comment]
Yep, All of the 8 tests with `USE_LATERAL_BOUNDARY_DIFFUSION = True` passed the BASELINE test.

**Comment by alperaltuntas** [comment]
update: answer changes in aux_mom tests as expected.

**Pull request merged**
