### PR TITLE
Merge main candidate 2021-02-19

### PR DESCRIPTION
**Pull request by alperaltuntas**
Merges the main candidate from GFDL:

https://github.com/NOAA-GFDL/MOM6/pull/1328

Source code tree hasn't been changed yet, so no MOM_interface change is needed.

testing: aux_mom.cheyenne_{intel,gnu}

### CODE REVIEW

**Comment by gustavo-marques** [comment]
@alperaltuntas, can you please reduce the line length in:
config_src/mct_driver/mom_surface_forcing_mct.F90, line 499
This has been caught in the new set of tests.

Also, it looks like one of the tests in near_boundary_unit_tests is failing. I will look into that.

**Comment by gustavo-marques** [comment]
@alperaltuntas, did you have to resolve conflicts in `MOM_lateral_boundary_diffusion.F90`? If so, this could be the reason why one of the unit tests is failing. Should I send a PR to main_candidate_2021-02-19 fixing this?

**Comment by alperaltuntas** [comment]
> can you please reduce the line length in

done.

> did you have to resolve conflicts in MOM_lateral_boundary_diffusion.F90

Yes. Check out the following comparison vs. the original candidate.

https://github.com/NOAA-GFDL/MOM6/compare/dev-gfdl-main-candidate-2021-02-19...NCAR:main_candidate_2021-02-19

> Should I send a PR to main_candidate_2021-02-19 fixing this

Yes, please.

**Comment by gustavo-marques** [comment]
@alperaltuntas, the unit test is still failing and I could not replicate that. Any idea why unit tests are passing in https://github.com/NCAR/MOM6/pull/178 and not in this PR?

**Comment by alperaltuntas** [comment]
@gustavo-marques weird. will look into it.

**Comment by alperaltuntas** [comment]
@gustavo-marques It looks like the MOM_lateral_boundary_diffusion unit tests are already failing in the current dev/ncar, but are passing in main_candidate_2021-02-19. I confirmed that that's the case by running the unit tests on Cheyenne with gnu. So, I believe, once this PR gets merged, the unit tests will be fixed.

**Comment by gustavo-marques** [comment]
Ok, thanks. Will merge this now.

**Pull request merged**
