### PR TITLE
Accommodate multi-instance runs in CESM

### PR DESCRIPTION
**Pull request by alperaltuntas**
This PR introduces changes that are mainly in NUOPC cap, infra/FMS, and src/framework to accommodate multi-instance runs in CESM:

Changes in nuopc cap:
 - receive instance id and suffix from the CESM coupler.
 - call `ensemble_manager_init`. This makes sure the input/output files contain the instance suffix.
 - add instance suffix to log files, restart files, and rpointer.

Changes in infra/FMS{1,2}:
 - add the optional `ensumble_suffix` arg to  `ensemble_manager_init`.  If provided, this arg bypasses the call to `FMS_ensemble_manager_init`, and instead, calls `fms_io_set_filename_appendix` and `fms2_io_set_filename_appendix`. This makes sure that all i/o files managed my FMS contains the ensemble suffix.

Change in src/framework:
 - append instance suffix to MOM_parameter_doc* files. ( I believe this is the only change that may potentially impact GFDL's ensemble workflow.)

This PR should be evaluating in conjunction with https://github.com/ESCOMP/MOM_interface/pull/137.

I am mentioning @MJHarrison-GFDL, @marshallward, and @hkershaw-brown in case they'd prefer to review this PR before it gets merged to dev/ncar. If so, please let us know and will hold off until you review.

### CODE REVIEW

**Comment by marshallward** [comment]
The changes to MOM and the FMS infra should be fine.  I have a pending PR which removes the references to `fms_io_mod` in the FMS2 ensemble manager, but that conflict should not be difficult to resolve when it happens.

(I would suggest looking into squashing and rebasing some of these commits though!)

**Comment by hkershaw-brown** [comment]
I ran an 8 instance case with this, looks good.

**Comment by alperaltuntas** [comment]
@gustavo-marques , I just realized there is a conflict due to the latest PR merge. I'll address that.

**Comment by alperaltuntas** [comment]
@gustavo-marques this is ready to merge. You can squash and merge. To run with multiple instances you can set `./xmlchange NINST_OCN=N` where N is the number of MOM6 instances you'd like to run with.

**Review by gustavo-marques — APPROVED** [review]

**Pull request merged**
