### PR TITLE
Merge dev master candidate 2019 08 30

### PR DESCRIPTION
**Pull request by gustavo-marques**
We have already checked that these commits do not change answers for NCAR but it would be good to check this again. I had to manually merge the latest dev/ncar due to a conflict in MOM_thickness_diffuse.F90.

### CODE REVIEW

**Comment by alperaltuntas** [comment]
tx0.66v1 tests are bit for bit but gx1v6 answers change. Is it expected?

**Comment by gustavo-marques** [comment]
I suspect this is because we still have USE_MEKE = True in this configuration. Did we have the same problem in a previous PR?

**Comment by alperaltuntas** [comment]
Right. Any idea why travis is failing?

**Comment by gustavo-marques** [comment]
No. Test tc0 in symmetric mode is the one failing...

**Comment by gustavo-marques** [comment]
Finally, it passed all the tests.

**Pull request merged**
