### PR TITLE
Improve Leith schemes

### PR DESCRIPTION
**Pull request by gustavo-marques**
*Follow @Hallberg-NOAA suggestions to improve/correct the Leith implementation in MOM_lateral_mixing_coeffs.F90:
   - remove unnecessary halo updates
   - change loop indices
   - make expressions rotationally symmetric
   - fix bugs in vort_xy_dy and grid_sp_v2
   - remove unnecessary code

* @septicscuzzy noticed a few mistakes in the Leith AH coefficient calculation that are now fixed:
  - Use inv_PI6 instead of inv_PI5
  - Use Del2vort_q instead of vert_vort_mag

These modifications will not change answers since none of these options are currently tested.

### CODE REVIEW

**Review by alperaltuntas — APPROVED** [review]
testing: aux_mom/cheyenne b4b

**Comment by alperaltuntas** [comment]
This passes our tests but there are conflicts in MOM_hor_visc. @gustavo-marques  can you resolve the conflicts?

**Review by alperaltuntas — CHANGES_REQUESTED** [review]
conflicts need to be resolved

**Comment by gustavo-marques** [comment]
> This passes our tests but there are conflicts in MOM_hor_visc. @gustavo-marques can you resolve the conflicts?

Yes, I will resolve that. Thanks.

**Pull request merged**
