### PR TITLE
dimension rescaling fixes and CFC cleanup

### PR DESCRIPTION
**Pull request by klindsay28**
correct scale argument in get_param and chksum calls

add dimension scaling terms to some expressions

add some chksum calls

### CODE REVIEW

**Review by gustavo-marques — APPROVED** [review]

**Comment by gustavo-marques** [comment]
Thanks, @klindsay28. Just highlighting that, with the changes proposed in this PR, the workhorse CESM/MOM6 passes the unit scaling tests. We should discuss with @alperaltuntas how to incorporate these tests into one of the CESM Test suites.

**Comment by alperaltuntas** [comment]
> ...CESM/MOM6 passes the unit scaling tests

@gustavo-marques , when I set `T_RESCALE_POWER = 11`, I get answer changes in ocean.stats with GMOM_JRA.TL319_t061, even before merging this PR. Which configuration have you tested the unit scaling.

**Comment by klindsay28** [comment]
> > ...CESM/MOM6 passes the unit scaling tests
> 
> @gustavo-marques , when I set `T_RESCALE_POWER = 11`, I get answer changes in ocean.stats with GMOM_JRA.TL319_t061, even before merging this PR. Which configuration have you tested the unit scaling.

@alperaltuntas , we indeed were not passing dimension rescaling tests prior to this PR. The first commit of the PR gets the tests passing for non-CFC runs. I verified this with each `RESCALE_POWER` parameter separately set to 20 and -20. I compared ocean.stats.nc, chksum output from DEBUG=True, and some history output that I had written out every timestep.

The other commits get the test to pass with the CFC tracers turned on, though you do need to set `CFC11_IC_VAL` and `CFC12_IC_VAL` to non-zero values. I checked this with each `RESCALE_POWER` parameter separately set to 20. I also checked the combination `L_RESCALE_POWER=10,Z_RESCALE_POWER=11,T_RESCALE_POWER=13`.

This testing was primarily with a GMOM experiment with the NUOPC driver. I also did non-CFC testing with MCT (CFC_cap is not implemented for MCT).

**Comment by alperaltuntas** [comment]
Thanks @klindsay28 for the explanation! I just confirmed that the PR fixes the scaling of my test case as well. I'll look into adding dimensional scaling tests to our aux_mom test suite. Not sure if there is a suitable test type tough. Seems like `REP` is the best candidate when combined with some hack I am thinking of. Will check with CSEG.

**Review by alperaltuntas — APPROVED** [review]

**Comment by klindsay28** [comment]
I'm definitely in favor of testing this in aux_mom.

A test that might serve as a useful example is [CTSM's ciso test](https://github.com/ESCOMP/CTSM/blob/master/cime_config/SystemTests/lciso.py). It confirms that turning on carbon isotopes doesn't change answers.

I think it would be helpful if we could compare multiple runs to a base, preferably in a single batch submission. I wonder how hard it would be to generalize CIME's `system_tests_compare_two` to `system_tests_compare_n`.

**Comment by alperaltuntas** [comment]
Thanks @klindsay28 . Sounds like the CTSM's ciso example is a great place to start. I'll investigate.

**Pull request merged**
