### PR TITLE
Fixes in MEKE that allows GME to work properly 

### PR DESCRIPTION
**Pull request by gustavo-marques**
Summary:

* Adds a new equilibrium formula for MEKE a4f9550;

* Rearranges MEKE_EQUILIBRIUM subroutine to avoid unnecessary calculations 839217d;

* Adds option to nudge MEKE to an equilibrium value. To select this option one needs to set MEKE_EQUILIBRIUM_RESTORING=True. The timescale for nudging is controlled via MEKE_RESTORING_TIMESCALE ebf5ee0.

This PR should not change answers since none of these options are enabled in our tests.

### CODE REVIEW

**Comment by gustavo-marques** [comment]
Test tc2 was failing because of some MEKE diagnostics. I've cherry-picked commit 3f041d93fbb784 from https://github.com/NOAA-GFDL/MOM6/pull/1014 that fixes these issues.

**Comment by marshallward** [comment]
I was able to reproduce this error on my desktop, and got the following error:
```
tc2.repro: At line 833 of file /home/marshall/gfdl/mom6_ncar/.testing//../src/parameterizations/lateral/MOM_MEKE.F90
tc2.repro: Fortran runtime error: Index '5' of dimension 2 of array 'cs%equilibrium_value' below lower bound of 2314885530818453536
tc2.repro: 
tc2.repro: Error termination. Backtrace:
tc2.repro: #0  0x55882b866c24 in ???
tc2.repro: #1  0x55882be1278d in ???
tc2.repro: #2  0x55882babd7d1 in ???
tc2.repro: #3  0x55882b7fdbbe in ???
tc2.repro: #4  0x7f27e3767152 in ???
tc2.repro: #5  0x55882b7fdbfd in ???
tc2.repro: #6  0xffffffffffffffff in ???
tc2.repro: --------------------------------------------------------------------------
tc2.repro: Primary job  terminated normally, but 1 process returned
tc2.repro: a non-zero exit code. Per user-direction, the job has been aborted.
tc2.repro: --------------------------------------------------------------------------
tc2.repro: --------------------------------------------------------------------------
tc2.repro: mpirun detected that one or more processes exited with non-zero status, thus causing
tc2.repro: the job to be terminated. The first process to do so was:
tc2.repro: 
tc2.repro:   Process name: [[16273,1],0]
tc2.repro:   Exit code:    2
tc2.repro: --------------------------------------------------------------------------
make: *** [Makefile:253: results/tc2/ocean.stats.repro] Error 1
```
I haven't looked at what's going on yet, but looks like `CS%equilibrium_value` may not have been initialized.  Hard for me to say for sure, if it was set outside of the function.

One bit of good news is that the updated Makefile will report this information more clearly when it's merged into dev/master.

**Comment by gustavo-marques** [comment]
Thanks, @marshallward. I was able to reproduce the error on Cheyenne with gnu/8.3.0. 
Allocating `CS%equilibrium_value` inside subroutine `MEKE_equilibrium_restoring` seems to solve the problem.

**Comment by marshallward** [comment]
This is suggesting to me that we need to continue doing an optimized test run (`REPRO=1`), even if we don't necessarily expect agreement with the unoptimized results.  I might modify the test to always run but only conditionally test the output.

**Pull request merged**
